tester.init({profileName="unnamed test",fixPath=true,func=function()
    context("luaiod",function()
        context("more inside?",function()
            it("you can do it!",function()end)
        end)
        it("has promise support?",function()
            test.isExist(promise):failMsg("Module not exist")
            global.hello = true
        end)
        it("has thread based worker support?",function()
            test.isExist(require"worker")
            test.isExist(global.hello)
        end)
        context("this is... ERROR?!",function()
            it("and show what line made it!",function()
                test.isExist(nil):failMsg("You can add test case fail message too")
            end)
        end)
    end)
end})
